spring.application.name=Authentication-Jwt
spring.output.ansi.enabled=always

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/Authentication_Jwt_DB
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=f204a4e6a1fe307ab43ef2480e7f7210ab41219a9a209962a66d2894b481b872
jwt.expiration=360000
#jwt.expiration=300000